CREATE TABLE IF NOT EXISTS links (
    id SERIAL PRIMARY KEY,
    short_url TEXT UNIQUE NOT NULL,
    original_url TEXT NOT NULL,
    time_creaded TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
